### ISSUE TITLE
clear rented book after unrent

### ISSUE THREAD

**Issue by ignatandrei** [ignatandrei/SimpleBookRental#38]

**Comment by ignatandrei** [comment]
do not disappear all

**Comment by ignatandrei** [comment]
const items =  ALL ITEMS , minus the id of the book unrented
this.listOfData = [...items];

**Comment by shdow** [comment]
fixed, please check the latest commit, waiting for approval

**Comment by ignatandrei** [comment]
Superb. Dar ai nevoie de 

this.listOfData = [...this.listOfData];

?

**Comment by shdow** [comment]
aparent, nu :D
