### ISSUE TITLE
Modify Api array

### ISSUE THREAD

**Issue by shdow** [ignatandrei/SimpleBookRental#7]
I've adapted react hooks to my code, unfortunately, I still get my state as undefined, I cand seem to find the problem but I think that there might be a solution.
I was wondering if you can remove the [] from the array so that it looks like this so that I can do some testing to see if it works, thank you.

  {
    "id": 1,
    "title": "1984",
    "description": null,
    "authors": [
      {
        "id": 2,
        "name": "Orwell, George"
      }
    ]
  },
  {
    "id": 2,
    "title": "Animal Farm",
    "description": null,
    "authors": [
      {
        "id": 2,
        "name": "Orwell, George"
      }
    ]
  },
  {
    "id": 3,
    "title": "A History of Religious Ideas (Vol. 1, Vol. 2, Vol. 3)",
    "description": null,
    "authors": [
      {
        "id": 3,
        "name": "Eliade, Mircea"
      }
    ]
  },
  {
    "id": 4,
    "title": "12 Rules for LifeAn Antidote to Chaos",
    "description": null,
    "authors": [
      {
        "id": 4,
        "name": "Peterson, Jordan B"
      }
    ]
  }

**Comment by ignatandrei** [comment]
From authors array - I can. From books array- does not make sense. How do you want the json?

**Comment by ignatandrei** [comment]
https://github.com/ignatandrei/SimpleBookRental/commit/17d3202e2e7f4b921865b8f50c535b39cbb842c8

**Comment by ignatandrei** [comment]
https://bookrentalapi20191216080922.azurewebsites.net/Book/GetBooks
